### ISSUE TITLE
InstaCapture crash after enable Proguard

### ISSUE THREAD

**Issue by bigant88** [tarek360/Instacapture#16]
03-02 17:50:15.383 17461-17461/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.InternalError
                                                       at g.d.d.b.y.a(Unknown Source)
                                                       at g.d.d.b.h.<clinit>(Unknown Source)
                                                       at g.d.d.a.a(Unknown Source)
                                                       at g.d.d.a.<init>(Unknown Source)
                                                       at g.d.d.a.<init>(Unknown Source)
                                                       at g.d.d.c$1.<init>(Unknown Source)
                                                       at g.d.d.c.<clinit>(Unknown Source)
                                                       at g.b.a(Unknown Source)
                                                       at com.tarek360.instacapture.InstaCapture.b(Unknown Source)
                                                       at com.tarek360.instacapture.InstaCapture.a(Unknown Source)
                                                       at com.tarek360.instacapture.InstaCapture.a(Unknown Source)
                                                       at place.where.common.view.fragment.IndoorMapFragment.onIndoorShareCLick(Unknown Source)
                                                       at place.where.common.view.fragment.IndoorMapFragment$$ViewBinder$4.doClick(Unknown Source)
                                                       at butterknife.internal.DebouncingOnClickListener.onClick(Unknown Source)
                                                       at android.view.View.performClick(View.java:4757)
                                                       at android.view.View$PerformClick.run(View.java:19766)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5255)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
                                                    Caused by: java.lang.NoSuchFieldException: producerIndex
                                                       at java.lang.Class.getDeclaredField(Class.java:886)
                                                       at g.d.d.b.y.a(Unknown Source) 
                                                       at g.d.d.b.h.<clinit>(Unknown Source) 
                                                       at g.d.d.a.a(Unknown Source) 
                                                       at g.d.d.a.<init>(Unknown Source) 
                                                       at g.d.d.a.<init>(Unknown Source) 
                                                       at g.d.d.c$1.<init>(Unknown Source) 
                                                       at g.d.d.c.<clinit>(Unknown Source) 
                                                       at g.b.a(Unknown Source) 
                                                       at com.tarek360.instacapture.InstaCapture.b(Unknown Source) 
                                                       at com.tarek360.instacapture.InstaCapture.a(Unknown Source) 
                                                       at com.tarek360.instacapture.InstaCapture.a(Unknown Source) 
                                                       at place.where.common.view.fragment.IndoorMapFragment.onIndoorShareCLick(Unknown Source) 
                                                       at place.where.common.view.fragment.IndoorMapFragment$$ViewBinder$4.doClick(Unknown Source) 
                                                       at butterknife.internal.DebouncingOnClickListener.onClick(Unknown Source) 
                                                       at android.view.View.performClick(View.java:4757) 
                                                       at android.view.View$PerformClick.run(View.java:19766) 
                                                       at android.os.Handler.handleCallback(Handler.java:739) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5255) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by tarek360** [comment]
Hi, please provide unobfuscated stack trace.
