### ISSUE TITLE
java.lang.NoClassDefFoundError: rx.plugins.RxJavaHooks

### ISSUE THREAD

**Issue by juyingguo** [tarek360/Instacapture#20]
java.lang.NoClassDefFoundError: rx.plugins.RxJavaHooks
	at rx.Observable.create(Observable.java:98)
	at rx.Observable.defer(Observable.java:1773)
	at com.tarek360.instacapture.screenshot.ViewsBitmapObservable.get(ViewsBitmapObservable.kt:20)
	at com.tarek360.instacapture.screenshot.ScreenshotProvider.getScreenshotBitmap(ScreenshotProvider.kt:16)
	at com.tarek360.instacapture.Instacapture.captureRx(Instacapture.kt:58)
	at com.tarek360.instacapture.Instacapture.capture(Instacapture.kt:31)

**Comment by juyingguo** [comment]
i add the below code in gradle

    compile 'com.github.tarek360:instacapture:2.0.0-kotlin-beta1'
 
    compile files('libs/rxjava-1.1.9.jar')

**Comment by tarek360** [comment]
You can remove `compile files('libs/rxjava-1.1.9.jar')`, Instacapture already use RxJava v1.1.9
if the crash still exists let me know.

**Comment by juyingguo** [comment]
compile 'com.github.tarek360:instacapture:2.0.0-beta1'  ，ok

**Comment by tarek360** [comment]
What is your question please?
