### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by wangyangke** [tarek360/Instacapture#35]
my code :
      Instacapture.capture(this, object : SimpleScreenCapturingListener() {
                override fun onCaptureComplete(bitmap: Bitmap) {
                    shere(bitmap)
                }
            })
        }

error：

06-20 11:52:01.472 32477-32477/com.jisu.sports E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jisu.sports, PID: 32477
    java.lang.NoClassDefFoundError: Failed resolution of: Lrx/functions/Func0;
        at com.tarek360.instacapture.screenshot.ScreenshotProvider.getScreenshotBitmap(ScreenshotProvider.kt:15)
        at com.tarek360.instacapture.Instacapture.captureRx(Instacapture.kt:58)
        at com.tarek360.instacapture.Instacapture.capture(Instacapture.kt:31)
        at com.jisu.sports.ui.matche.view.MatchDetailsActivity$initClick$1.onClick(MatchDetailsActivity.kt:121)
        at android.view.View.performClick(View.java:6266)
        at android.view.View$PerformClick.run(View.java:24730)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6684)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.functions.Func0" on path: DexPathList[[zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/base.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_dependencies_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_resources_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_0_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_1_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_2_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_3_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_4_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_5_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_6_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_7_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_8_apk.apk", zip file "/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/lib/arm, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/base.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_dependencies_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_resources_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_0_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_1_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_2_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_3_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_4_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_5_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_6_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_7_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_8_apk.apk!/lib/armeabi, /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_slice_9_apk.apk!/lib/armeabi, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.tarek360.instacapture.screenshot.ScreenshotProvider.getScreenshotBitmap(ScreenshotProvider.kt:15) 
        at com.tarek360.instacapture.Instacapture.captureRx(Instacapture.kt:58) 
        at com.tarek360.instacapture.Instacapture.capture(Instacapture.kt:31) 
        at com.jisu.sports.ui.matche.view.MatchDetailsActivity$initClick$1.onClick(MatchDetailsActivity.kt:121) 
        at android.view.View.performClick(View.java:6266) 
        at android.view.View$PerformClick.run(View.java:24730) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6684) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.jisu.sports-3BldHbGLK4OEceox2rHrkA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
can you help me

**Comment by zdmelon** [comment]
same problem with you. Have you solved it?

**Comment by tarek360** [comment]
@zdmelon @wangyangke pls tell me what is your Kotlin version and if you use RxJava what is the version as well?

**Comment by anshulagarwal06** [comment]
@tarek360 : same issue with me.
Rxjava2 version : 2.0.2
Kotlin version : 1.2.10

**Comment by tarek360** [comment]
@anshulagarwal06 
I couldn't reproduce the issue but there is a fix in `Instacapture:2.0.1` maybe help pls update and let me know the result?
```gradle
  implementation 'com.github.tarek360:instacapture:2.0.1'
```

**Comment by anshulagarwal06** [comment]
Worked. 👍

**Comment by Legementarion** [comment]
@tarek360 Still have problem on 2.0.0, but on 2.0.1 works fine, pls update your readme, to avoid confusing with this issue
